### ISSUE TITLE
Headers cannot be a map as it is valid to specify HTTP headers more than once

### ISSUE THREAD

**Issue by lpil** [CrowdHailer/raxx#13]

**Comment by CrowdHailer** [comment]
Interesting. I did not know that. Whats the usecase for multiple header definitions.

**Comment by lpil** [comment]
`"Set-Cookie"` jumps out as being one you might use more than once. Either way it's in the spec.

**Comment by lpil** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by CrowdHailer** [comment]
I was thinking about that second option. returning empty lists for headers that are not present would possible be a nice way to have things work.

**Comment by CrowdHailer** [comment]
Also need to be aware that you can't set headers with new line charachters

**Comment by CrowdHailer** [comment]
Still undecided on this. the most convenient layout definitely varies by usecase.

three new points.
- Messing in the headers structure directly doesn't seam like a good idea so maybe it doesn't matter much.
- Keeping as a list allows a monotonic mapping between raxx response and http response
- its impossible to have a field that can be io_list or list of io_lists, no way to tell them apart.

**Comment by CrowdHailer** [comment]
Also I think Http poison normalises requests to be capitalised

**Comment by CrowdHailer** [comment]
from rfc 7230

> A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).

So maybe the map is still a way to go

**Comment by lpil** [comment]
What will you do about the exceptions?

**Comment by CrowdHailer** [comment]
I've started hiding header access behind module functions.

```
Request.location(request)
# vs
request.headers.location
```

So this means it matters a lot less. I think pattern matching on non option data of a request is useful. path, host etc but headers are meta data and so matching on them is probably the wrong call.

**Comment by lpil** [comment]
Since Elixir structs don't have private properties how do you prevent people from matching anyway?

**Comment by CrowdHailer** [comment]
I have no problem with people matching. the idea of a map for headers was to encourage matching. As you cannot match on a keyword list when you dont know the order. As far as I can work out

**Comment by CrowdHailer** [comment]
Can be a map when there is a way to join values. Equivalent to server sent events spec

```
data: line1
data: line2
```

```
{data: "line1\nline2"}
```
