### ISSUE TITLE
make `use Raxx.Middleware` a thing

### ISSUE THREAD

**Issue by nietaki** [CrowdHailer/raxx#149]
There are some situations where having default, no-op implementations for `Raxx.Middleware` callbacks could be useful - there's many middlewares that would only need to modify the request headers and forcing people to write the other callbacks is unproductive.

**Comment by CrowdHailer** [comment]
I think that the attached PR does everything we need for this.

@nietaki agree?

**Comment by nietaki** [comment]
yup
