### ISSUE TITLE
allow to set multiple cookies

### ISSUE THREAD

**Issue by SchrodingerZhu** [CrowdHailer/raxx#163]
I have to use `Map.update!` to set multiple cookies now. I suggest we should allow user to insert multiple `set-cookie` items in header.

**Comment by CrowdHailer** [comment]
This makes sense. What API would you suggest? The cookie headers are special cases in HTTP requests because there are different rules for combining multiple cookie headers, so I've never been sure if this should live in Raxx core or the cookie project somehow

**Comment by CrowdHailer** [comment]
A new method to handle cookies makes sense, however everything relating to cookies I have extracted to the cookie project. https://hex.pm/packages/cookie

**Comment by CrowdHailer** [comment]
I think I will close this issue, in favour of improving the `:cookie` project.

**Comment by Nicd** [comment]
This issue should not be closed, because the cookie package does not handle `set-cookie` header at all. Currently it's not possible to have multiple `set-cookie` headers in Raxx and the cookie library cannot change that because it's a Raxx limitation.
