### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by Nezteb** [CrowdHailer/raxx#194]
The last update to raxx was in 2020, and there don't seem to be any active forks: https://useful-forks.github.io/?repo=CrowdHailer%2Fraxx

Is further maintenance planned? Has development paused in favor of some other successor library or project? Were there any wider ecosystem changes that have led to raxx development being put on hiatus indefinitely?

Note: I fully understand how difficult maintaining an open-source project is and that priorities change and life happens. I mean no ill will with my question. I just wanted to check in and see how the project was doing and if there's anything I can do to help I'd love to assist!

**Comment by CrowdHailer** [comment]
Hey. I guess it's paused, although I would cast my eye over pull requests if they appeared. 
I still use the project to start small servers, there is nothing broken in it that I know of.

Honestly, Raxx never felt like it found a place in the Elixir community. I explained my view of how Raxx came into existence by being simpler than Plug and focusing on functional purity in several talks. However, I don't think such a focus was very idiomatic for Elixir projects.

I mostly use gleam now, see issue #189 for a discussion I started in there.
