### ISSUE TITLE
Adding Cowboy to a supervision tree

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/raxx#31]
The cowboy adapter currently cannot be started under a project applications supervision tree.

Cowboy, by design, starts a server under its application supervision tree when using `:cowboy.start_http/4`.

It is possible to start it under a project supervisor. and we would like to add that functionality to the cowboy adapter.

See:
- [Best way to start a plug router under supervision](https://groups.google.com/forum/#!topic/elixir-lang-talk/fOzHc1rTEa4)
- [plug adapter for child spec](https://github.com/elixir-lang/plug/blob/master/lib/plug/adapters/cowboy.ex#L114)

**Comment by CharlesOkwuagwu** [comment]
Ok cool, so we switch to cowboy.child_spec. That would be better.

**Comment by CrowdHailer** [comment]
@CharlesOkwuagwu I have opened a PR #35 to tackle this. It's not using child_spec but I think an even better solution of just defining a start_link function. This is better because it allows you to start a application directly, useful for testing
