### ISSUE TITLE
Suggestion: upgrade to https://github.com/elli-lib/elli

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [CrowdHailer/raxx#33]
https://github.com/elli-lib/elli seems to be in active development.

Should we upgrade?

**Comment by CrowdHailer** [comment]
Sounds good. I just asked them about what changes might be forthcoming

**Comment by CharlesOkwuagwu** [comment]
We can aspire to this: http://ezgr.net/increasing-security-erlang-ssl-cowboy/

> All of the above options result in getting an A rating from SSLLabs, which is a good compromise between security and compatibility.

I'm still not sure how to make the suggested security updates to elli. 

These are the kind of things we can tackle together with the guys who actively maintain that elli fork I mentioned

**Comment by CrowdHailer** [comment]
I think I am entirely on board with making this switch. Sounds like it is active. Again I am currently focusing on some different areas but would accept a PR on this.

Also of note the the elli guys. I was not able to add all the Raxx features to the elli adapter. If you check the test suite in raxx_elli there are only two files(not three as in raxx_cowboy and ace_http) There were some issues with how elli worked when it came to implementing chunked responses

**Comment by CrowdHailer** [comment]
I am not currently using elli so will not be making this change myself. Anyone wishing to do this is welcome to open a PR
