### ISSUE TITLE
Implement `X-forwarded-for`

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/raxx#39]
## Resources

rails discusses how this updates looking up client ip
https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/middleware/remote_ip.rb

maybe this? https://tools.ietf.org/html/draft-petersson-forwarded-for-02

**Comment by kelvinst** [comment]
@CrowdHailer is there any way to get the client IP on Raxx servers today?

**Comment by CrowdHailer** [comment]
Ace stores, connection specific information in the Process dictionary https://gitlab.com/Nicd/tilastokeskus/blob/master/lib/reception/routes/page_view.ex#L108-111

*sidebar the [raxx slack channel](https://elixir-lang.slack.com/messages/C56H3TBH8/) is a good place for questions.*

@nietaki hmm I wonder if there is a better place for this information

**Comment by nietaki** [comment]
Good pointer, I'll add it to the brewing pot of Stack/RequestContext thoughts
