### ISSUE TITLE
Add middleware that closes connections on responses to `Connection: close` header

### ISSUE THREAD

**Issue by samphilipd** [CrowdHailer/raxx#44]
If we respond to a request with `Connection: close`, we should send a response with `Connection: close` and then close it ourselves.

This works around buggy clients that send `Connection: close` and never close the connection themselves.

**Comment by CrowdHailer** [comment]
I'm thinking these middleware should be defined in the Tokumei project. A bit like how the sinatra-contrib code extends rack. I want to slim down the raxx repo as much as possible over time until it is basically only the specification of an interface. (I think, this goal is up for discussion as I'm unsure)

**Comment by samphilipd** [comment]
Closed in favour of https://github.com/CrowdHailer/Tokumei/issues/33
