### ISSUE TITLE
Fail build if code is not formatted

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/raxx#59]
This will have to wait until the new year when elixir `1.6` is released. The CI tests should fail if running the formatter would result in a change to the code.

Not sure if such a mix task even exists, but I think it would be good. It would however mean that raxx required 1.6 to work. 

use
```
mix format --check-formatted mix.exs "{lib,test}/**/*.{ex,exs}"
```

**Comment by filipecabaco** [comment]
Maybe using something similar to https://docs.travis-ci.com/user/multi-os/#Example-Multi-OS-Build-Matrix with the `TRAVIS_ELIXIR_VERSION` environment variable?

This way it would be possible to have two commands:
- PRE-1.6: `if (( $(echo "$TRAVIS_ELIXIR_VERSION >= 1.6" | bc -l) ));  then echo 1; fi`
- POST-1.6: `if (( $(echo "$TRAVIS_ELIXIR_VERSION < 1.6" | bc -l) )); then echo 1; fi`

What do you think?

**Comment by CrowdHailer** [comment]
Sounds a good idea. Although I am tempted to only support the latest version of Elixir to keep maintaining the project simple.

**Comment by filipecabaco** [comment]
After talking with some friends actually I think you are right. Overall it makes more sense, it would only be overcomplicating at this point in time.

Maintaining older versions might not bring much benefit and it will only increase development time.
