### ISSUE TITLE
can we call set_query multiple times to add / change query params on the request

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [CrowdHailer/raxx#64]
[This line will only match requests where the query had not been set](https://github.com/CrowdHailer/raxx/blob/master/lib/raxx.ex#L235)

`def set_query(request = %Raxx.Request{query: nil}, query) do`

What if we want to set / append / or change the existing query?

**Comment by CrowdHailer** [comment]
I'm trying to make my helpers more restrictive than not. as a starting point. This point is one I think is interesting but counterpoints that I have thought of.
a) this will catch if anyone mistakenly sets query twice
b) There is ambiguity on how you might merge queries
d) the user can always fall back to `%{request | query: query}` if they really need it.

**Comment by CharlesOkwuagwu** [comment]
> a) this will catch if anyone mistakenly sets query twice

Then we make this explicit in the docs for that function, that clears the ambiguity

**Comment by CrowdHailer** [comment]
Are you able to add a comment in the docs that makes this clear to you?

**Comment by CharlesOkwuagwu** [comment]
i'll think of one
