### ISSUE TITLE
Some considerations for header fields

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [CrowdHailer/raxx#65]
https://github.com/CrowdHailer/raxx/blob/a73694e2d41aef8c33e6463d7e77753a3d03d951/lib/raxx.ex#L258-L260

We don't need to raise an error here. See this: https://stackoverflow.com/a/5259004/44080

> RFC 7230 explicitly states that field headers should be treated as case insensitive

**Comment by CharlesOkwuagwu** [comment]
Regarding duplicate header fields see https://tools.ietf.org/html/rfc7230#section-3.2.2

**Comment by CharlesOkwuagwu** [comment]
OK noted rfc7540

**Comment by CrowdHailer** [comment]
Can you add a point to the FAQ for this? :-)
