### ISSUE TITLE
Add middleware Raxx.Logger

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/raxx#73]
This should be started in a new repo and linked from the extensions section of this repo.
The hex project should be raxx_logger

- Logger should write a single line if response is sent in a complete state. i.e. when body is `false` or `binary()`
- Logger should write a line for first part of response and details of each chunk when response is streamed.
- Logger could use common logger format.
  - it could be customised using: https://www.ibm.com/support/knowledgecenter/en/ssw_i5_54/rzaie/rzaielogformat.htm
  - similar to old implementation here. https://github.com/CrowdHailer/Tokumei/blob/raxx-0.11.1/app/lib/tokumei/common_logger.ex

**Comment by CrowdHailer** [comment]
Far more complete common logger implementation

**Comment by lpil** [comment]
Is there an example of the middleware format and usage?
