### ISSUE TITLE
add middleware Raxx.CORS

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/raxx#85]
important security middleware.

- flowchart https://www.html5rocks.com/static/images/cors_server_flowchart.png
- plug implementation https://github.com/mschae/cors_plug

**Comment by felipesere** [comment]
I'd be keen to give this a try.
Would it live in this repo or outside as regular extension like
- [Raxx.MethodOverride](https://github.com/CrowdHailer/raxx_method_override)
- [Raxx.Static](https://github.com/CrowdHailer/raxx_static)
- [Raxx.ApiBlueprint](https://github.com/CrowdHailer/raxx_api_blueprint)

**Comment by CrowdHailer** [comment]
Happy either way. I think probably it would end up as a separate repo. But
you could start it here and I would extract it before releasing raxx 1.0

**Comment by CrowdHailer** [comment]
@felipesere Did you ever make any progress on this? The concept of middleware in Raxx hasn't really matured in the meantime.

**Comment by felipesere** [comment]
Oh not in ages. If someone wants to pick it up go for it.

**Comment by CrowdHailer** [comment]
Probably won't be picking it up right now but I think  it can happily get marked as a post 1.0 issue

**Comment by CrowdHailer** [comment]
Extracted to a standalone project https://github.com/CrowdHailer/CORS
